// Package grpcgw runs a grpc-gateway (REST → gRPC transcoding) HTTP server
// as a shost.Service. It owns the gateway boilerplate: the runtime.ServeMux,
// the client connection to the gRPC endpoint, handler registration, and the
// HTTP server lifecycle with readiness and graceful shutdown.
//
// Registration functions are the ones generated by protoc-gen-grpc-gateway:
//
//	gw := grpcgw.New(":8081", "localhost:9090",
//		grpcgw.Register(pb.RegisterGreeterHandler),
//		grpcgw.Register(pb.RegisterOrdersHandler),
//	)
//	host := shost.New().
//		AddService(grpcsvc.New(":9090", grpcServer)).
//		AddService(gw).
//		MustBuild()
//
// Separate go module: unlike the shost core, it depends on
// github.com/grpc-ecosystem/grpc-gateway/v2 and google.golang.org/grpc.
package grpcgw

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"sync"
	"sync/atomic"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

// RegisterFunc registers generated gateway handlers on the mux through the
// gRPC client connection — the signature of protoc-generated
// RegisterXxxHandler functions.
type RegisterFunc func(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error

// Service runs a grpc-gateway HTTP server as a shost.Service.
type Service struct {
	name      string
	addr      string
	endpoint  string
	registers []RegisterFunc
	muxOpts   []runtime.ServeMuxOption
	dialOpts  []grpc.DialOption
	configure func(*http.Server)
	wrap      func(http.Handler) http.Handler

	ready     chan struct{}
	readyOnce sync.Once
	listAddr  atomic.Value // string, set once listening

	mu  sync.Mutex
	srv *http.Server // set once Start builds it, for Stop
}

// Option customizes a Service.
type Option func(*Service)

// Register adds a generated gateway registration function. At least one is
// required.
func Register(fn RegisterFunc) Option {
	if fn == nil {
		panic("grpcgw: Register called with nil function")
	}
	return func(s *Service) { s.registers = append(s.registers, fn) }
}

// WithName overrides the default service name ("grpc-gateway <addr>").
func WithName(name string) Option {
	return func(s *Service) { s.name = name }
}

// WithServeMuxOptions passes options to runtime.NewServeMux (marshalers,
// header matchers, error handlers).
func WithServeMuxOptions(opts ...runtime.ServeMuxOption) Option {
	return func(s *Service) { s.muxOpts = append(s.muxOpts, opts...) }
}

// WithDialOptions replaces the default dial options (insecure transport)
// used for the client connection to the gRPC endpoint.
func WithDialOptions(opts ...grpc.DialOption) Option {
	return func(s *Service) { s.dialOpts = opts }
}

// WithServer customizes the underlying *http.Server (timeouts, TLS config,
// error log) before it starts.
func WithServer(configure func(*http.Server)) Option {
	return func(s *Service) { s.configure = configure }
}

// WithHandler wraps the gateway mux with HTTP middleware (logging, CORS,
// auth); the returned handler serves all requests.
func WithHandler(wrap func(http.Handler) http.Handler) Option {
	return func(s *Service) { s.wrap = wrap }
}

// New creates a gateway service listening on addr and forwarding to the
// gRPC server at endpoint. By default the connection to endpoint is
// plaintext (the usual same-host gateway setup); override with
// WithDialOptions. It panics when no Register option is given —
// configuration is a programmer error.
func New(addr, endpoint string, opts ...Option) *Service {
	s := &Service{
		name:     "grpc-gateway " + addr,
		addr:     addr,
		endpoint: endpoint,
		ready:    make(chan struct{}),
	}
	for _, opt := range opts {
		opt(s)
	}
	if len(s.registers) == 0 {
		panic("grpcgw: New requires at least one Register option")
	}
	return s
}

func (s *Service) Name() string { return s.name }

// Ready implements shost.Readier: the channel closes once handlers are
// registered and the listener is accepting connections.
func (s *Service) Ready() <-chan struct{} { return s.ready }

// Addr returns the actual listen address (useful with ":0"), or "" before
// the service is ready.
func (s *Service) Addr() string {
	if v := s.listAddr.Load(); v != nil {
		return v.(string)
	}
	return ""
}

// Start dials the gRPC endpoint, registers the gateway handlers, then
// listens and serves until the host initiates shutdown. Graceful
// termination is driven by Stop; Start unblocks when Serve returns.
func (s *Service) Start(ctx context.Context) error {
	dialOpts := s.dialOpts
	if dialOpts == nil {
		dialOpts = []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials())}
	}
	conn, err := grpc.NewClient(s.endpoint, dialOpts...)
	if err != nil {
		return fmt.Errorf("grpcgw: dial %s: %w", s.endpoint, err)
	}
	defer conn.Close()

	mux := runtime.NewServeMux(s.muxOpts...)
	for _, register := range s.registers {
		if err := register(ctx, mux, conn); err != nil {
			return fmt.Errorf("grpcgw: register handler: %w", err)
		}
	}

	var handler http.Handler = mux
	if s.wrap != nil {
		handler = s.wrap(handler)
	}
	srv := &http.Server{Addr: s.addr, Handler: handler}
	if s.configure != nil {
		s.configure(srv)
	}
	s.mu.Lock()
	s.srv = srv
	s.mu.Unlock()

	ln, err := net.Listen("tcp", s.addr)
	if err != nil {
		return fmt.Errorf("grpcgw: listen %s: %w", s.addr, err)
	}
	s.listAddr.Store(ln.Addr().String())
	s.readyOnce.Do(func() { close(s.ready) })

	serveErr := make(chan error, 1)
	go func() { serveErr <- srv.Serve(ln) }()

	select {
	case err := <-serveErr:
		if errors.Is(err, http.ErrServerClosed) {
			return nil
		}
		return err
	case <-ctx.Done():
		// Shutdown is driven by Stop; wait for Serve to drain.
		err := <-serveErr
		if errors.Is(err, http.ErrServerClosed) {
			return ctx.Err()
		}
		return err
	}
}

// Stop gracefully shuts the server down under ctx's deadline; when the
// deadline expires, remaining connections are closed forcefully.
func (s *Service) Stop(ctx context.Context) error {
	s.mu.Lock()
	srv := s.srv
	s.mu.Unlock()
	if srv == nil {
		return nil
	}
	err := srv.Shutdown(ctx)
	if err == nil {
		return nil
	}
	if errors.Is(err, context.DeadlineExceeded) || errors.Is(err, context.Canceled) {
		srv.Close()
		return fmt.Errorf("grpcgw: graceful shutdown timed out, connections closed forcefully: %w", err)
	}
	return err
}
