package sdnotify

import (
	"fmt"
	"strings"
	"time"
)

// UnitConfig describes a systemd unit generated by Unit.
type UnitConfig struct {
	// Description is the human-readable unit description.
	Description string
	// ExecStart is the full command line (required).
	ExecStart string
	// User runs the service under the given account when set.
	User string
	// WorkingDirectory is optional.
	WorkingDirectory string
	// Environment lists KEY=value pairs.
	Environment []string
	// WatchdogSec enables the systemd watchdog; pair with sdnotify.Bind,
	// which starts the keep-alive pinger automatically.
	WatchdogSec time.Duration
	// TimeoutStopSec bounds shutdown; align it with the host's
	// WithShutdownTimeout (systemd should wait at least as long as the
	// host drains). Zero keeps the systemd default (90s).
	TimeoutStopSec time.Duration
}

// Unit renders a Type=notify systemd unit for a shost application —
// a starting point for installers; write it to
// /etc/systemd/system/<name>.service. Restart=on-failure complements
// shost's own restart policies: WithRestart supervises individual
// services inside the process, systemd restarts the process itself.
func Unit(cfg UnitConfig) string {
	var b strings.Builder
	b.WriteString("[Unit]\n")
	if cfg.Description != "" {
		fmt.Fprintf(&b, "Description=%s\n", cfg.Description)
	}
	b.WriteString("After=network.target\n\n")

	b.WriteString("[Service]\n")
	b.WriteString("Type=notify\n")
	fmt.Fprintf(&b, "ExecStart=%s\n", cfg.ExecStart)
	if cfg.User != "" {
		fmt.Fprintf(&b, "User=%s\n", cfg.User)
	}
	if cfg.WorkingDirectory != "" {
		fmt.Fprintf(&b, "WorkingDirectory=%s\n", cfg.WorkingDirectory)
	}
	for _, env := range cfg.Environment {
		fmt.Fprintf(&b, "Environment=%s\n", env)
	}
	if cfg.WatchdogSec > 0 {
		fmt.Fprintf(&b, "WatchdogSec=%d\n", int(cfg.WatchdogSec.Seconds()))
	}
	if cfg.TimeoutStopSec > 0 {
		fmt.Fprintf(&b, "TimeoutStopSec=%d\n", int(cfg.TimeoutStopSec.Seconds()))
	}
	b.WriteString("Restart=on-failure\n\n")

	b.WriteString("[Install]\nWantedBy=multi-user.target\n")
	return b.String()
}
